### ISSUE TITLE
Add all the Managers

### ISSUE THREAD

**Issue by Mapsred** [Mapsred/TicketingBundle#9]
Create a Manager class for each entities : 

By following the examples you need to create and configure a Manager for each entity.

Don't forget to define it as a service, with the tag and with the right class parameter (from the bundle config)

```php
<?php

namespace Maps_red\TicketingBundle\Manager;


class TicketStatusManager extends AbstractManager
{
}
```

```yaml
# Resources/config/services.yaml
services:
#...
    Maps_red\TicketingBundle\Manager\TicketStatusManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_status'}
```
